hotel/src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $datein;

    /**
     * @ORM\Column(type="date")
     */
    private $dateout;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $status;
    
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDatein(): ?\DateTimeInterface
    {
        return $this->datein;
    }

    public function setDatein(\DateTimeInterface $datein): self
    {
        $this->datein = $datein;

        return $this;
    }

    public function getDateout(): ?\DateTimeInterface
    {
        return $this->dateout;
    }

    public function setDateout(\DateTimeInterface $dateout): self
    {
        $this->dateout = $dateout;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(?string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }
}

hotel/src/Controller/ReservationController.php
<?php

namespace App\Controller;


use App\Entity\Reservation;
use App\Entity\Room;
use App\Repository\ReservationRepository;
use App\Repository\RoomRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/room", name="reservations")
 */
class ReservationController extends AbstractController
{
    public function index()
    {
        
    }


    /**
     * @Route("/res/{id}", name="res")
     */

    public function reserve(Request $request, Room $room ){
        $reserv = new Reservation();
        
        $resform = $this->createFormBuilder()
            ->add('datein', DateType::class, [
                'widget' => 'choice',
                'label' => 'Date d\'entrée'
            ])
            ->add('dateout', DateType::class, [
                'widget' => 'choice',
                'label' => 'Date d\'sortie',
                'attr' => ['placeholder' => 'Nom Prénom']
            ])
            ->add('email', EmailType::class, [
                'label' => 'Email',
                'attr' => ['placeholder' => 'Email']
            ])
            //-----------
            ->add('status', TextType::class, [
                'label' => ' Nom',
                'attr' => ['placeholder' => 'Nom Prénom']
            ] )
            //-----------
            ->add('Enregistrer', SubmitType::class)
            ->getForm()
        ;

        $resform->handleRequest($request);

        if($resform->isSubmitted()){
            $input = $resform->getData();

            $res = new Reservation();
            $res->setDatein($input['datein']);

            $res->setDateout($input['dateout']);

            $res->setStatus($input['status']);

            $res->setEmail($input['email']);

            $res->setName($room->getName());

            $res->setCategory($room->getCategory());

            $res->setPrice($room->getPrice());

            

            $em = $this->getDoctrine()->getManager();
            $em->persist($res);
            $em->flush();

            

            $this->addFlash('res', 'Votre réservation a été prise en compte, merci de régler sur place' );


            //return $this->redirect($this->generateUrl('home'));
        }

        
    

        return $this->render('reservation/index.html.twig', [
            'resform' => $resform->createView()
        ]);

    }


    /**
     * @Route("/reservations", name="reserved")
     */


    
    public function show(ReservationRepository $resrep)
    {
        
        $res = $resrep->findAll();


        return $this->render('reservation/res.html.twig', [
            'res' => $res
        ]);

    }

    //-----------------------------------------

    






    //-----------------------------------------


    






    //-----------------------------------------








    /**
     * @Route("/reservations/delete/{id}", name="reservedDelete")
     */


     public function delete($id, ReservationRepository $resdel){
        $em = $this->getDoctrine()->getManager();
        $res = $resdel->find($id);
        $em->remove($res);
        $em->flush();

        //messagge
        $this->addFlash('success', 'La réservation a été supprimé avec succès' );
        return $this->redirect($this->generateUrl('reservationsreserved'));

     }



    

    

    
    
    
}

hotel/templates/reservation/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{%for message in app.flashes('res')%}

    <div class="alert alert-success" >
        <h3> {{message}} </h3>
		
    </div>    
{% endfor %}
<br>
<div class="container" >
	{{form(resform)}}
    <p> ou réservez votre chambre chez <a href="https://www.booking.com/index.fr.html?aid=376366;label=fr-85Sbyi2evytni3mHZEi6UgS267492169156%3Apl%3Ata%3Ap1%3Ap22.563.000%3Aac%3Aap%3Aneg%3Afi%3Atikwd-65526620%3Alp9055230%3Ali%3Adec%3Adm%3Appccp%3DUmFuZG9tSVYkc2RlIyh9Ye7BFAsTyVd6vvamF_no64o;sid=f25ab19291eaaadc82b380f133905df8;keep_landing=1;redirected=1;source=country&gclid=Cj0KCQjwxtSSBhDYARIsAEn0thSjKFnKkRGVB7sC2zQAAefImgR65LDSpU_sj6mLfbyvcDs4OagdgVgaAqMEEALw_wcB&" >Booking.com</a> </p>
    
</div>









{% endblock %}

hotel/templates/reservation/res.html.twig
{% extends 'base.html.twig' %}



{% block body %}
{%for message in app.flashes('success')%}

    <div class="alert alert-success" >
        <h3> {{message}} </h3>
    </div>    
{% endfor %}

<br>
<div class="container" >
    
    <h2> Réservations </h2>
    <br>
    <table class="table table-striped" >
        <thead>
            <tr>
                <td>Suite</td> 
                <td>Hotel</td> 
                <td>Client</td>    
                <td>Entrée</td>    
                <td>Sortie</td>
                <td>Email</td>   
                <td>Supprimer</td>
            </tr>
            </thead> 
            <tbody>

                
                
                {% for re in res %}
                
                
                
                    <tr>

                        <td> {{re.name}} </td>       
                        <td> {{re.category}} </td>       
                        <td> {{re.status}} </td>    
                        <td> {{re.datein|date("m/d/Y") }} </td>
                        <td> {{re.dateout|date("m/d/Y")}} </td> 
                        <td> {{re.email}} </td>
                        
                        <td><a class="btn btn-outline-danger btn-sm" href=" {{path ('reservationsreservedDelete', {id: re.id})}} " >  Supprimer   </a></td>
                        
                    </tr>
                
                {% endfor %}
            </tbody>

    </table>
</div>
{% endblock %}